version: "3.9"
services:
  vector:
    image: timberio/vector:latest-alpine
    volumes:
      - ./vector.toml:/etc/vector/vector.toml
    ports:
      # Prom Exporter (localhost:8000/metrics)
      - 8000:8000
      # Datadog agent
      - 9000:9000
      # HTTP server
      - 7000:7000
    depends_on:
      - prom
      - loki
  prom:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom-storage:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - prom
    volumes:
      - grafana-storage:/var/lib/grafana
  loki:
    image: grafana/loki:latest
    volumes:
      - loki-storage:/var/log
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  grafana-storage:
    driver: local
  prom-storage:
    driver: local
  loki-storage:
    driver: local
