[sources.host]
type = "host_metrics"
scrape_interval_secs = 15

[sources.internal]
type = "internal_metrics"
scrape_interval_secs = 15

[sources.datadog]
type = "datadog_agent"
address = "0.0.0.0:9000"

[sinks.prom]
type = "prometheus_exporter"
inputs = ["host", "internal", "datadog"]
address = "0.0.0.0:8000"
default_namespace = "service"
